name: Run Automation

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install System Tools
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Install Python Libraries
        run: |
          pip install moviepy edge-tts faster-whisper

      - name: Run Automation Script
        run: |
          python3 main.py

      - name: Upload Output
        uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: output/
