name: Run Automation

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install System Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python Libraries
        run: |
          python3 -m pip install --upgrade pip
          pip install moviepy imageio imageio-ffmpeg

      - name: Run Script
        run: |
          python3 main.py

      - name: Upload Output
        uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: output/
